# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_client
from signrequest_client.models.document_team import DocumentTeam  # noqa: E501
from signrequest_client.rest import ApiException


class TestDocumentTeam(unittest.TestCase):
    """DocumentTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentTeam(self):
        """Test DocumentTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signrequest_client.models.document_team.DocumentTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
