# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_client
from signrequest_client.models.document_signrequest import DocumentSignrequest  # noqa: E501
from signrequest_client.rest import ApiException


class TestDocumentSignrequest(unittest.TestCase):
    """DocumentSignrequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentSignrequest(self):
        """Test DocumentSignrequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signrequest_client.models.document_signrequest.DocumentSignrequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
