# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.documents_search_api import DocumentsSearchApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestDocumentsSearchApi(unittest.TestCase):
    """DocumentsSearchApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.documents_search_api.DocumentsSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_documents_search_list(self):
        """Test case for documents_search_list

        Search documents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
