# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.document_attachments_api import DocumentAttachmentsApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestDocumentAttachmentsApi(unittest.TestCase):
    """DocumentAttachmentsApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.document_attachments_api.DocumentAttachmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_document_attachments_create(self):
        """Test case for document_attachments_create

        Create a Document Attachment  # noqa: E501
        """
        pass

    def test_document_attachments_list(self):
        """Test case for document_attachments_list

        Retrieve a list of Document Attachments  # noqa: E501
        """
        pass

    def test_document_attachments_read(self):
        """Test case for document_attachments_read

        Retrieve a Document Attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
