# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.teams_api import TeamsApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_teams_create(self):
        """Test case for teams_create

        Create a Team  # noqa: E501
        """
        pass

    def test_teams_invite_member(self):
        """Test case for teams_invite_member

        Invite a Team Member  # noqa: E501
        """
        pass

    def test_teams_list(self):
        """Test case for teams_list

        Retrieve a list of Teams  # noqa: E501
        """
        pass

    def test_teams_partial_update(self):
        """Test case for teams_partial_update

        Update a Team  # noqa: E501
        """
        pass

    def test_teams_read(self):
        """Test case for teams_read

        Retrieve a Team  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
