# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.documents_api import DocumentsApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.documents_api.DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_documents_create(self):
        """Test case for documents_create

        Create a Document  # noqa: E501
        """
        pass

    def test_documents_delete(self):
        """Test case for documents_delete

        Delete a Document  # noqa: E501
        """
        pass

    def test_documents_delete_files(self):
        """Test case for documents_delete_files

        Delete a Document's Files  # noqa: E501
        """
        pass

    def test_documents_list(self):
        """Test case for documents_list

        Retrieve a list of Documents  # noqa: E501
        """
        pass

    def test_documents_read(self):
        """Test case for documents_read

        Retrieve a Document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
