# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.models.invite_member import InviteMember  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestInviteMember(unittest.TestCase):
    """InviteMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInviteMember(self):
        """Test InviteMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signrequest_python_client.models.invite_member.InviteMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
