# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.models.file_from_sf import FileFromSf  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestFileFromSf(unittest.TestCase):
    """FileFromSf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileFromSf(self):
        """Test FileFromSf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signrequest_python_client.models.file_from_sf.FileFromSf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
