# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.api_tokens_api import ApiTokensApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestApiTokensApi(unittest.TestCase):
    """ApiTokensApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.api_tokens_api.ApiTokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_tokens_create(self):
        """Test case for api_tokens_create

        Create an API token  # noqa: E501
        """
        pass

    def test_api_tokens_delete(self):
        """Test case for api_tokens_delete

        Delete an API token  # noqa: E501
        """
        pass

    def test_api_tokens_list(self):
        """Test case for api_tokens_list

        Retrieve a list of API tokens  # noqa: E501
        """
        pass

    def test_api_tokens_read(self):
        """Test case for api_tokens_read

        Retrieve an API token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
