# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_client
from signrequest_client.models.document_signing_log import DocumentSigningLog  # noqa: E501
from signrequest_client.rest import ApiException


class TestDocumentSigningLog(unittest.TestCase):
    """DocumentSigningLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentSigningLog(self):
        """Test DocumentSigningLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = signrequest_client.models.document_signing_log.DocumentSigningLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
