# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.webhooks_api import WebhooksApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.webhooks_api.WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhooks_create(self):
        """Test case for webhooks_create

        Create a Webhook  # noqa: E501
        """
        pass

    def test_webhooks_delete(self):
        """Test case for webhooks_delete

        Delete a Webhook  # noqa: E501
        """
        pass

    def test_webhooks_list(self):
        """Test case for webhooks_list

        Retrieve a list of Webhooks  # noqa: E501
        """
        pass

    def test_webhooks_partial_update(self):
        """Test case for webhooks_partial_update

        Partially update a Webhook  # noqa: E501
        """
        pass

    def test_webhooks_read(self):
        """Test case for webhooks_read

        Retrieve a Webhook  # noqa: E501
        """
        pass

    def test_webhooks_update(self):
        """Test case for webhooks_update

        Update a Webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
