# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.team_members_api import TeamMembersApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestTeamMembersApi(unittest.TestCase):
    """TeamMembersApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.team_members_api.TeamMembersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_team_members_list(self):
        """Test case for team_members_list

        Retrieve a list of Team Members  # noqa: E501
        """
        pass

    def test_team_members_read(self):
        """Test case for team_members_read

        Retrieve a Team Member  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
