# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import signrequest_python_client
from signrequest_python_client.api.signrequests_api import SignrequestsApi  # noqa: E501
from signrequest_python_client.rest import ApiException


class TestSignrequestsApi(unittest.TestCase):
    """SignrequestsApi unit test stubs"""

    def setUp(self):
        self.api = signrequest_python_client.api.signrequests_api.SignrequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_signrequests_cancel_signrequest(self):
        """Test case for signrequests_cancel_signrequest

        Cancel a SignRequest  # noqa: E501
        """
        pass

    def test_signrequests_create(self):
        """Test case for signrequests_create

        Create a SignRequest  # noqa: E501
        """
        pass

    def test_signrequests_list(self):
        """Test case for signrequests_list

        Retrieve a list of SignRequests  # noqa: E501
        """
        pass

    def test_signrequests_read(self):
        """Test case for signrequests_read

        Retrieve a SignRequest  # noqa: E501
        """
        pass

    def test_signrequests_resend_signrequest_email(self):
        """Test case for signrequests_resend_signrequest_email

        Resend a SignRequest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
