# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301
import os

NAME = "signrequest-python-client"
VERSION = "1.0.0"


def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()


# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    author="Michaël Krens",
    author_email="michael@signrequest.com",
    description="A python client to use the SignRequest REST api",
    url="https://github.com/SignRequest/signrequest-python-client/",
    keywords=["SignRequest", "SignRequest API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=read("README.md")
)
