# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301
import os

NAME = "signrequest-python-client"
VERSION = "2.0.0"

def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name='signrequest-python-client',
    version=VERSION,
    description="SignRequest API",
    author_email="tech-support@signrequest.com",
    url="https://github.com/SignRequest/signrequest-python-client/",
    keywords=["SignRequest", "SignRequest API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=read("README.md"),
    long_description_content_type="text/markdown"
)
