# coding: utf-8

"""
    SignRequest API

    API for SignRequest.com

    OpenAPI spec version: v1
    Contact: tech-support@signrequest.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlinePrefillTags(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'external_id': 'str',
        'text': 'str',
        'checkbox_value': 'bool',
        'date_value': 'date'
    }

    attribute_map = {
        'external_id': 'external_id',
        'text': 'text',
        'checkbox_value': 'checkbox_value',
        'date_value': 'date_value'
    }

    def __init__(self, external_id=None, text=None, checkbox_value=None, date_value=None):  # noqa: E501
        """InlinePrefillTags - a model defined in Swagger"""  # noqa: E501

        self._external_id = None
        self._text = None
        self._checkbox_value = None
        self._date_value = None
        self.discriminator = None

        if external_id is not None:
            self.external_id = external_id
        if text is not None:
            self.text = text
        if checkbox_value is not None:
            self.checkbox_value = checkbox_value
        if date_value is not None:
            self.date_value = date_value

    @property
    def external_id(self):
        """Gets the external_id of this InlinePrefillTags.  # noqa: E501


        :return: The external_id of this InlinePrefillTags.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this InlinePrefillTags.


        :param external_id: The external_id of this InlinePrefillTags.  # noqa: E501
        :type: str
        """
        if external_id is not None and len(external_id) > 255:
            raise ValueError("Invalid value for `external_id`, length must be less than or equal to `255`")  # noqa: E501

        self._external_id = external_id

    @property
    def text(self):
        """Gets the text of this InlinePrefillTags.  # noqa: E501


        :return: The text of this InlinePrefillTags.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this InlinePrefillTags.


        :param text: The text of this InlinePrefillTags.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def checkbox_value(self):
        """Gets the checkbox_value of this InlinePrefillTags.  # noqa: E501


        :return: The checkbox_value of this InlinePrefillTags.  # noqa: E501
        :rtype: bool
        """
        return self._checkbox_value

    @checkbox_value.setter
    def checkbox_value(self, checkbox_value):
        """Sets the checkbox_value of this InlinePrefillTags.


        :param checkbox_value: The checkbox_value of this InlinePrefillTags.  # noqa: E501
        :type: bool
        """

        self._checkbox_value = checkbox_value

    @property
    def date_value(self):
        """Gets the date_value of this InlinePrefillTags.  # noqa: E501


        :return: The date_value of this InlinePrefillTags.  # noqa: E501
        :rtype: date
        """
        return self._date_value

    @date_value.setter
    def date_value(self, date_value):
        """Sets the date_value of this InlinePrefillTags.


        :param date_value: The date_value of this InlinePrefillTags.  # noqa: E501
        :type: date
        """

        self._date_value = date_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlinePrefillTags):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
